# Generated by Django 5.0.3 on 2024-03-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('race', models.CharField(max_length=20)),
                ('hometown', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=5)),
                ('char_type', models.CharField(max_length=20)),
                ('img', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Esper',
            fields=[
                ('name_esper', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('sign', models.CharField(max_length=50)),
                ('element', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
