name: FFXII API test

on: [pull_request, push]

jobs:
  ffxii-api-test:
    runs-on: ubunto-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Using Django
        
        run: |
          pip install -r requirements.txt
          py manage.py test
